name: Application CI
on: [push, pull_request]
jobs:
    validation:
        name: "Gradle Wrapper Validation"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
    pipeline:
        name: as-cms-translation-pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            PROJECT_ID: ${{ secrets.GKE_PROJECT }}
            GKE_CLUSTER: citizenjournalist
            DEPLOYMENT_NAME: ascmstranslation
            IMAGE: europe-west6-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/citizenjournalist/as-cms-translation
            GKE_ZONE: europe-west6-a
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            NG_CLI_ANALYTICS: false
            NODE_VERSION: 16.17.1
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: '17.x'
            - name: Package application
              run: npm run java:jar:prod
            - id: 'auth'
              name: 'Authenticate to Google Cloud'
              uses: google-github-actions/auth@v0.4.0
              with:
                credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
            - name: Login to GAR
              uses: docker/login-action@v1
              with:
                registry: europe-west6-docker.pkg.dev
                username: _json_key
                password: '${{ secrets.GOOGLE_CREDENTIALS }}'

            # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v0'
            - run: |
                # Set up docker to authenticate
                # via gcloud command-line tool.
                gcloud auth configure-docker europe-west6-docker.pkg.dev
            - name: Build and publish docker image
              if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
              run: |
                  GIT_TAG=:${GITHUB_REF#refs/tags/}
                  DOCKER_TAG=${GIT_TAG#:refs/heads/main}
                  echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
                  ./gradlew jib -Pprod -Djib.to.image=$IMAGE${DOCKER_TAG}
          # Get the GKE credentials so we can deploy to the cluster
            - name: Set up GKE credentials
              uses: google-github-actions/get-gke-credentials@v0
              with:
                cluster_name: ${{ env.GKE_CLUSTER }}
                location: ${{ env.GKE_ZONE }}
          # Deploy the Docker image to the GKE cluster
            - name: Deploy
              if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/'))
              run: |-
                # replacing the image name in the k8s template
                kubectl set image  deploy/$DEPLOYMENT_NAME $DEPLOYMENT_NAME-app=$IMAGE${DOCKER_TAG}
